# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/Universal_ila_0_0.xci
# IP: The module: 'Universal_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Universal_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Universal_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/Universal_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Universal_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/Universal_ila_0_0.xci
# IP: The module: 'Universal_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Universal_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Universal_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Universal/Universal.srcs/sources_1/bd/Universal/ip/Universal_ila_0_0/Universal_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Universal_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
