# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/Universal/Universal.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Universal || ORIG_REF_NAME==Universal} -quiet] -quiet

# IP: bd/Universal/ip/Universal_c_addsub_0_0/Universal_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Universal_c_addsub_0_0 || ORIG_REF_NAME==Universal_c_addsub_0_0} -quiet] -quiet

# IP: bd/Universal/ip/Universal_vio_0_0/Universal_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Universal_vio_0_0 || ORIG_REF_NAME==Universal_vio_0_0} -quiet] -quiet

# IP: bd/Universal/ip/Universal_ila_0_0/Universal_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Universal_ila_0_0 || ORIG_REF_NAME==Universal_ila_0_0} -quiet] -quiet

# XDC: bd/Universal/Universal_ooc.xdc
